version: 0.2

env:
  variables:
    CARGO_FLAGS: "-j 4"

phases:
  build:
    commands:
      - build.sh openssl-devel > lambda.zip

artifacts:
  files:
    - lambda.zip

cache:
  paths:
    - '/root/.cargo/**/*'